import {
  Clock,
  Timer,
  CupSoda,
  Percent,
  Star,
  Gift,
  Trophy,
  Coins,
  Gem,
  Crown,
  Flame,
  Heart,
  Zap,
  Coffee,
  Pizza,
  Beer,
  Ticket,
  Gamepad2,
  Dices,
  Medal,
  Target,
  Rocket,
  Key,
  Lock,
  Smile,
  ThumbsUp,
  Music,
  Headphones,
  Camera,
  PartyPopper,
  Cake,
  Flag,
  Shield,
  Sparkles,
  Sun,
  Moon,
  Snowflake,
  Anchor,
  Umbrella,
  Leaf,
  PawPrint,
  Bell,
  Lightbulb,
  Puzzle,
  Magnet,
  Diamond,
  type LucideIcon,
} from 'lucide-react'

export const ICON_MAP: Record<string, LucideIcon> = {
  clock: Clock,
  clockBig: Timer,
  cup: CupSoda,
  percent: Percent,
  star: Star,
  gift: Gift,
  trophy: Trophy,
  coin: Coins,
  gem: Gem,
  crown: Crown,
  fire: Flame,
  heart: Heart,
  bolt: Zap,
  coffee: Coffee,
  pizza: Pizza,
  beer: Beer,
  ticket: Ticket,
  gamepad: Gamepad2,
  dice: Dices,
  medal: Medal,
  target: Target,
  rocket: Rocket,
  key: Key,
  lock: Lock,
  smile: Smile,
  thumbsUp: ThumbsUp,
  music: Music,
  headphones: Headphones,
  camera: Camera,
  party: PartyPopper,
  cake: Cake,
  flag: Flag,
  shield: Shield,
  sparkles: Sparkles,
  sun: Sun,
  moon: Moon,
  snow: Snowflake,
  anchor: Anchor,
  umbrella: Umbrella,
  leaf: Leaf,
  paw: PawPrint,
  bell: Bell,
  lightbulb: Lightbulb,
  puzzle: Puzzle,
  magnet: Magnet,
  diamond: Diamond,
}

export type IconKey = keyof typeof ICON_MAP

// Для селектора иконок в админке (вкладка «Призы»).
export const ICON_OPTIONS = Object.keys(ICON_MAP) as IconKey[]

export function Icon({ icon, className }: { icon: string; className?: string }) {
  const Cmp = ICON_MAP[icon] || Star
  return <Cmp className={className} strokeWidth={1.6} />
}

// Case-иконка (логотип кейса на главном экране) — отдельная, не выбирается.
export function CaseMark({ className }: { className?: string }) {
  return <Gift className={className} strokeWidth={1.6} />
}
